FROM alpine:3.22

LABEL org.opencontainers.image.authors=leleliu008@gmail.com

ADD ppkg /usr/bin/

RUN apk update && apk add --no-cache g++ libc-dev linux-headers

ENV GITHUB_ACTIONS=true

ENTRYPOINT [ "/bin/bash", "-l" ]
