#!/bin/sh

set -ex

mport() {
    if [ "$(id -u)" -eq 0 ] ; then
        command      mport "$@"
    else
        command sudo mport "$@"
    fi
}

package_name_transform_from_uppm_to_mport() {
    case $1 in
        gm4)      printf '%s\n' 'm4'        ;;
        grep)     printf '%s\n' 'gnugrep'   ;;
        golang)   printf '%s\n' 'go122'     ;;
        yq)       printf '%s\n' 'go-yq'     ;;
        xz)       printf '%s\n' 'gtar'      ;;
        bsdtar)   printf '%s\n' 'gtar'      ;;
        ed)       printf '%s\n' 'gsed'      ;;
        pkg-config) printf '%s\n' 'pkgconf' ;;
        perl)     printf '%s\n' 'perl5.38'  ;;
        *)        printf '%s\n' "$1"
    esac
}

main() {
    case $1 in
        about)
            mport -v
            ;;
        update)
            mport index
            ;;
        install)
            shift 1
            for UPPM_PACKAGE_NAME in "$@"
            do
                MPORT_PACKAGE_NAME="$(package_name_transform_from_uppm_to_mport "$UPPM_PACKAGE_NAME")"
                mport install "$MPORT_PACKAGE_NAME" || true
            done
            ;;
        is-installed)
            shift 1
            MPORT_PACKAGE_NAME="$(package_name_transform_from_uppm_to_mport "$1")"
            mport verify "$MPORT_PACKAGE_NAME" 2>/dev/null
            ;;
        info)
            shift 1
            case $2 in
                installed-dir)
                    #printf '%s\n' '/usr/local'
                    ;;
            esac
            ;;
        *)  mport "$@"
    esac
}

main "$@"
