#!/bin/sh

set -ex

package_name_transform_from_uppm_to_apt() {
    case $1 in
        gm4)      printf '%s\n' 'm4'        ;;
        gtar)     printf '%s\n' 'tar'       ;;
        gsed)     printf '%s\n' 'sed'       ;;
        gmake)    printf '%s\n' 'make'      ;;
        gindent)  printf '%s\n' 'indent'    ;;
        python3)  printf '%s\n' 'python3 python3-dev' ;;
        bsdtar)   printf '%s\n' 'libarchive-tools' ;;
        pkg-config) printf '%s\n' 'pkgconf' ;;
        glib-tools) printf '%s\n' 'glib'    ;;
        gettext-tools) printf '%s\n' 'gettext' ;;
        perl)     printf '%s\n' 'perl perl-doc' ;;
        *)        printf '%s\n' "$1"
    esac
}

main() {
    case $1 in
        about)
            apt --version
            ;;
        update)
            apt update
            ;;
        install)
            shift 1
            for UPPM_PACKAGE_NAME in "$@"
            do
                APK_PACKAGE_NAME="$(package_name_transform_from_uppm_to_apt "$UPPM_PACKAGE_NAME")"
                apt install -y $APK_PACKAGE_NAME
            done
            ;;
        is-installed)
            shift 1
            APK_PACKAGE_NAME="$(package_name_transform_from_uppm_to_apt "$1")"
            apt info "$APK_PACKAGE_NAME" 2>/dev/null
            ;;
        info)
            shift 1
            case $2 in
                installed-dir)
                    printf '%s\n' '/usr'
                    ;;
            esac
            ;;
        *)  apt "$@"
    esac
}

main "$@"
