name: AlpineLinux

on:
  push:
    branches: [ master, dev, tmp ]
  pull_request:
    branches: [ master, dev, tmp ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        tag: ['3.22', '3.21', '3.20', '3.19', '3.18', '3.17', '3.16', '3.15', '3.14', '3.13']

    container: alpine:${{ matrix.tag }}

    steps:
      - uses: actions/checkout@v4

      - run: ./ppkg --help
      - run: ./ppkg --version

      - run: ./ppkg setup

      - run: ./ppkg about

      - run: ./ppkg integrate zsh

      - run: ./ppkg update

      - run: ./ppkg search lib
      - run: ./ppkg search uctags


      - run: ./ppkg info-available uctags
      - run: ./ppkg info-available uctags --yaml
      - run: ./ppkg info-available uctags --json
      - run: ./ppkg info-available uctags version
      - run: ./ppkg info-available uctags license
      - run: ./ppkg info-available uctags summary
      - run: ./ppkg info-available uctags web-url
      - run: ./ppkg info-available uctags git-url
      - run: ./ppkg info-available uctags git-sha
      - run: ./ppkg info-available uctags git-ref
      - run: ./ppkg info-available uctags src-url
      - run: ./ppkg info-available uctags src-sha

      - run: ./ppkg depends uctags

      - run: ./ppkg install uctags

      - run: ./ppkg tree uctags

      - run: ./ppkg info-installed uctags installed-dir
      - run: ./ppkg info-installed uctags installed-files
      - run: ./ppkg info-available uctags version
      - run: ./ppkg info-installed uctags builtat-iso-8601-utc
      - run: ./ppkg info-installed uctags builtat-iso-8601
      - run: ./ppkg info-installed uctags builtat-rfc-3339
      - run: ./ppkg info-installed uctags builtat-iso-8601-utc
      - run: ./ppkg info-installed uctags builtat-rfc-3339-utc

      - run: ./ppkg bundle uctags .tar.gz
      - run: ./ppkg bundle uctags .tar.lz
      - run: ./ppkg bundle uctags .tar.xz
      - run: ./ppkg bundle uctags .tar.bz2
      - run: ./ppkg bundle uctags .zip

      - run: apk add alpine-sdk

      # https://wiki.alpinelinux.org/wiki/Include:Abuild-keygen
      # https://github.com/alpinelinux/abuild/blob/master/abuild-keygen.in
      - run: openssl genrsa -out leleliu008@gmail.com.rsa 2048
      - run: openssl rsa     -in leleliu008@gmail.com.rsa -pubout -out leleliu008@gmail.com.rsa.pub

      - run: cp leleliu008@gmail.com.rsa.pub /etc/apk/keys/

      - run: install -d ~/.abuild/
      - run: printf 'PACKAGER_PRIVKEY="%s"\n' "$PWD/leleliu008@gmail.com.rsa" > ~/.abuild/abuild.conf

      - run: ./ppkg export uctags .apk
      - run: ./ppkg export uctags ~/.apk
      - run: ./ppkg export uctags a/b.apk

      - run: apk add a/b.apk
      - run: apk info -L uctags

      - run: |
          printf '%s\n' 'version: 1000' >> ~/.ppkg/repos.d/official-core/formula/libyaml.yml

      - run: ./ppkg ls-available
      - run: ./ppkg ls-installed
      - run: ./ppkg ls-outdated

      - run: ./ppkg is-available uctags
      - run: ./ppkg is-installed uctags
      - run: ./ppkg is-outdated  libyaml


      - run: ./ppkg upgrade   uctags
      - run: ./ppkg reinstall uctags
      - run: ./ppkg uninstall uctags

      - run: ./ppkg fetch curl

      - run: ./ppkg cleanup

      - run: ./ppkg upgrade-self

      - run: ./ppkg formula-repo-list

      - run: ./ppkg formula-repo-add my_repo1 https://github.com/leleliu008/ppkg-formula-repository-official-core
      - run: ./ppkg formula-repo-add my_repo2 https://github.com/leleliu008/ppkg-formula-repository-official-core --branch=master
      - run: ./ppkg formula-repo-add my_repo3 https://github.com/leleliu008/ppkg-formula-repository-official-core --unpin
      - run: ./ppkg formula-repo-add my_repo4 https://github.com/leleliu008/ppkg-formula-repository-official-core --unpin --disable

      - run: ./ppkg formula-repo-list

      - run: ./ppkg formula-repo-init my_repo10 https://github.com/leleliu008/ppkg-formula-repository-official-core
      - run: ./ppkg formula-repo-init my_repo11 https://github.com/leleliu008/ppkg-formula-repository-official-core --branch=main
      - run: ./ppkg formula-repo-init my_repo12 https://github.com/leleliu008/ppkg-formula-repository-official-core --unpin
      - run: ./ppkg formula-repo-init my_repo13 https://github.com/leleliu008/ppkg-formula-repository-official-core --unpin --disable

      - run: ./ppkg formula-repo-list

      - run: ./ppkg formula-repo-conf my_repo1 --url=https://github.com/leleliu008/ppkg-formula-repository-official-core
      - run: ./ppkg formula-repo-conf my_repo2 --branch=master --unpin
      - run: ./ppkg formula-repo-conf my_repo3 --pin
      - run: ./ppkg formula-repo-conf my_repo4 --pin --enable

      - run: ./ppkg formula-repo-list

      - run: ./ppkg formula-repo-sync my_repo2

      - run: ./ppkg formula-repo-info my_repo2

      - run: ./ppkg formula-repo-del my_repo1
