name: build ppkg-core for linux manully

on:
  workflow_dispatch:
    inputs:
      target-arch:
        description: choose a target arch to be built for
        type: choice
        options:
          - x86_64
          - aarch64
          - ppc64le
          - riscv64
          - loongarch64
          - s390x
          - armhf
          - armv7
          - x86


jobs:

  linux:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: curl -LO https://raw.githubusercontent.com/alpinelinux/alpine-chroot-install/master/alpine-chroot-install
      - run: chmod +x alpine-chroot-install
      - run: sudo ./alpine-chroot-install -d /alpine -a ${{ github.event.inputs.target-arch }}
      - run: /alpine/enter-chroot /bin/sh .github/build-core.sh `date +%Y.%m.%d`
      - run: /alpine/destroy
      - run: ls -l

      - uses: actions/upload-artifact@v4
        with:
          name: ppkg-core---linux-${{ matrix.target-arch }}.tar.xz
          path: ppkg-core-*.tar.xz
