name: openSUSE

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  opensuse:
    strategy:
      fail-fast: false
      matrix:
        flavor: ['tumbleweed', 'leap:15.4']

    runs-on: ubuntu-latest

    container: opensuse/${{ matrix.flavor }}

    steps:
      - run: zypper update  -y
      - run: zypper install -y git cmake ninja gcc pkg-config libcurl-devel libgit2-devel libarchive-devel libyaml-devel libjansson-devel sqlite3-devel

      - uses: actions/checkout@main

      - run:  cmake -S . -B   build.d -G Ninja -DCMAKE_INSTALL_PREFIX=./output -DCMAKE_VERBOSE_MAKEFILE=ON
      - run:  cmake --build   build.d
      - run:  cmake --install build.d


      - run: |
          cat > ~/.gitconfig <<EOF
          [user]
            email = leleliu008@gmail.com
            name = leleliu008
          EOF


      - run: ./output/bin/ppkg

      - run: ./output/bin/ppkg --help
      - run: ./output/bin/ppkg -h

      - run: ./output/bin/ppkg --version
      - run: ./output/bin/ppkg -V

      - run: ./output/bin/ppkg setup -v

      - run: ./output/bin/ppkg env
      - run: ./output/bin/ppkg env -v

      - run: ./output/bin/ppkg integrate zsh
      - run: ./output/bin/ppkg integrate zsh -v

      - run: ./output/bin/ppkg update

      - run: ./output/bin/ppkg search lib
      - run: ./output/bin/ppkg search zip

      - run: ./output/bin/ppkg info @all
      - run: ./output/bin/ppkg info libzip
      - run: ./output/bin/ppkg info libzip --yaml
      - run: ./output/bin/ppkg info libzip --json
      - run: ./output/bin/ppkg info libzip summary
      - run: ./output/bin/ppkg info libzip version
      - run: ./output/bin/ppkg info libzip license
      - run: ./output/bin/ppkg info libzip web-url
      - run: ./output/bin/ppkg info libzip src-url
      - run: ./output/bin/ppkg info libzip src-sha

      - run: ./output/bin/ppkg depends libzip
      - run: ./output/bin/ppkg depends libzip -t dot
      - run: ./output/bin/ppkg depends libzip -t box

      - run: ./output/bin/ppkg fetch gzip
      - run: ./output/bin/ppkg fetch gsed -v

      - run: zypper install -y gcc-c++

      - run: ./output/bin/ppkg install libzip

      - run: ./output/bin/ppkg tree libzip

      - run: ./output/bin/ppkg info libzip installed-dir
      - run: ./output/bin/ppkg info libzip installed-files
      - run: ./output/bin/ppkg info libzip receipt-path
      - run: ./output/bin/ppkg info libzip receipt-json
      - run: ./output/bin/ppkg info libzip receipt-yaml
      - run: ./output/bin/ppkg info libzip installed-timestamp-unix
      - run: ./output/bin/ppkg info libzip installed-timestamp-iso-8601
      - run: ./output/bin/ppkg info libzip installed-timestamp-rfc-3339
      - run: ./output/bin/ppkg info libzip installed-version

      - run: ./output/bin/ppkg pack libzip
      - run: ./output/bin/ppkg pack libzip -t tar.gz
      - run: ./output/bin/ppkg pack libzip -t tar.lz
      - run: ./output/bin/ppkg pack libzip -t tar.xz
      - run: ./output/bin/ppkg pack libzip -t tar.bz2
      - run: ./output/bin/ppkg pack libzip -t zip

      - run: |
          printf '%s\n' 'version: 1000' >> ~/.ppkg/repos.d/offical-core/formula/libzip.yml

      - run: ./output/bin/ppkg ls-available
      - run: ./output/bin/ppkg ls-installed
      - run: ./output/bin/ppkg ls-outdated

      - run: ./output/bin/ppkg is-available libzip
      - run: ./output/bin/ppkg is-installed libzip
      - run: ./output/bin/ppkg is-outdated  libzip

      - run: ./output/bin/ppkg upgrade   libzip
      - run: ./output/bin/ppkg reinstall libzip
      - run: ./output/bin/ppkg uninstall libzip

      - run: ./output/bin/ppkg formula-repo-list
      - run: ./output/bin/ppkg formula-repo-add my_repo https://github.com/leleliu008/ppkg-formula-repository-offical-core
      - run: ./output/bin/ppkg formula-repo-del my_repo

      - run: ./output/bin/ppkg cleanup

        #- run: ./output/bin/ppkg upgrade-self
