name: publish ppkg docker image

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

on:
  workflow_dispatch:

jobs:

  # https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions

  single-arch:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, alpine]
        arch: [amd64, arm64/v8, riscv64, ppc64le, s390x]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - id: version
        run: printf 'version=%s\n' "$(./ppkg -V)" >> "$GITHUB_OUTPUT"

      - if: matrix.arch != 'amd64'
        uses: docker/setup-qemu-action@v3

      - id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.${{ matrix.os }}
          platforms: linux/${{ matrix.arch }}
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.os }}/${{ matrix.arch }}:latest,ghcr.io/${{ github.repository }}/${{ matrix.os }}/${{ matrix.arch }}:${{ steps.version.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}/${{ matrix.os }}/${{ matrix.arch }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true


  # https://docs.docker.com/build/ci/github-actions/multi-platform/

  multip-arch:

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, alpine]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - id: version
        run: printf 'version=%s\n' "$(./ppkg -V)" >> "$GITHUB_OUTPUT"

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.${{ matrix.os }}
          platforms: linux/amd64,linux/arm64/v8,linux/riscv64,linux/ppc64le,linux/s390x
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.os }}:latest,ghcr.io/${{ github.repository }}/${{ matrix.os }}:${{ steps.version.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}/${{ matrix.os }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true


  loong64:

    strategy:
      fail-fast: false
      matrix:
        os: [alpine, debian]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - id: version
        run: printf 'version=%s\n' "$(./ppkg -V)" >> "$GITHUB_OUTPUT"

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.${{ matrix.os }}.loong64
          platforms: linux/loong64
          push: true
          tags: ghcr.io/${{ github.repository }}/${{ matrix.os }}/loong64:latest,ghcr.io/${{ github.repository }}/${{ matrix.os }}/loong64:${{ steps.version.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}/${{ matrix.os }}/loong64
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true


  openeuler-multip-arch:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - id: version
        run: printf 'version=%s\n' "$(./ppkg -V)" >> "$GITHUB_OUTPUT"

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.openeuler
          platforms: linux/amd64,linux/arm64,linux/loong64
          push: true
          tags: ghcr.io/${{ github.repository }}/openeuler:latest,ghcr.io/${{ github.repository }}/openeuler:${{ steps.version.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}/openeuler
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true


  openeuler-single-arch:

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu, alpine]
        arch: [amd64, arm64, loong64]

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}

      - id: version
        run: printf 'version=%s\n' "$(./ppkg -V)" >> "$GITHUB_OUTPUT"

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.openeuler
          platforms: ${{ matrix.arch }}
          push: true
          tags: ghcr.io/${{ github.repository }}/openeuler/${{ matrix.arch }}:latest,ghcr.io/${{ github.repository }}/openeuler/${{ matrix.arch }}:${{ steps.version.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}

      - uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/${{ github.repository }}/openeuler/${{ matrix.arch }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
