name: publish ppkg core

on:
  workflow_dispatch:

jobs:

  base:
    runs-on: ubuntu-latest

    steps:

      - id:  calculate-release-version
        run: |
          RELEASE_VERSION="$(date +%Y.%m.%d)"

          printf 'RELEASE_VERSION=%s\n' "$RELEASE_VERSION" >> "$GITHUB_OUTPUT"

    outputs:
      release-version: ${{ steps.calculate-release-version.outputs.RELEASE_VERSION }}


  macos:
    needs: base

    runs-on: macos-14

    strategy:
      fail-fast: false
      matrix:
        target-version: ['10.15', '11.0', '12.0', '13.0', '14.0', '15.0']
        target-arch: [x86_64, arm64]

    steps:
      - uses: actions/checkout@v4

      - run: ./ppkg setup
      - run: ./ppkg update
      - run: ./ppkg install macos-${{ matrix.target-version }}-${{ matrix.target-arch }}/uppm@0.15.4
      - run: ./ppkg bundle  macos-${{ matrix.target-version }}-${{ matrix.target-arch }}/uppm@0.15.4 .tar.xz

      - run: rm core/check-if-has-dynamic-section.c core/list-section-names.c core/print-*-if-present.c core/wrapper-template.c core/AppRun.c

      - run: |
          set -ex

          CC="$(xcrun --sdk macosx --find clang)"
          SYSROOT="$(xcrun --sdk macosx --show-sdk-path)"
          CFLAGS="-isysroot $SYSROOT -mmacosx-version-min=${{ matrix.target-version }} -arch ${{ matrix.target-arch }} -Qunused-arguments"

          for f in *.c
          do
            o="${f%.c}.exe"
            $CC $CFLAGS -std=c99 -Os -flto -o "$o" "$f"
            strip "$o"
          done

      - run: ./pack-ppkg-core ${{ needs.base.outputs.release-version }} macos-${{ matrix.target-version }}-${{ matrix.target-arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: ppkg-core-${{ needs.base.outputs.release-version }}-macos-${{ matrix.target-version }}-${{ matrix.target-arch }}.tar.xz
          path: ppkg-core-${{ needs.base.outputs.release-version }}-macos-${{ matrix.target-version }}-${{ matrix.target-arch }}.tar.xz


  linux:
    needs: base

    strategy:
      fail-fast: false
      matrix:
        target-arch: [loongarch64, x86_64, aarch64, riscv64, ppc64le, s390x]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          cat > run.sh <<EOF
          set -e

          COLOR_GREEN='\033[0;32m'        # Green
          COLOR_PURPLE='\033[0;35m'       # Purple
          COLOR_OFF='\033[0m'             # Reset

          echo() {
              printf '%b\n' "\$*"
          }

          run() {
              echo "\${COLOR_PURPLE}==>\${COLOR_OFF} \${COLOR_GREEN}\$@\${COLOR_OFF}"
              eval "\$*"
          }

          run uname -a

          run apk update
          run apk add curl tar xz g++ libc-dev linux-headers

          for item in *.c
          do
            gcc -std=c99 -Os -flto -Wl,-s -static -o "\${item%.c}.exe" "\$item"
          done

          export GITHUB_ACTIONS=true

          run ./ppkg setup --syspm
          run ./ppkg update
          run ./build-core.sh
          run ./ppkg install uppm@0.15.4 --static
          run ./ppkg bundle  uppm@0.15.4 .tar.xz
          EOF

      - run: ./pack-ppkg-core ${{ needs.base.outputs.release-version }} linux-${{ matrix.target-arch }}

      - uses: actions/upload-artifact@v4
        with:
          name: ppkg-core-${{ needs.base.outputs.release-version }}-linux-${{ matrix.target-arch }}.tar.xz
          path: ppkg-core-${{ needs.base.outputs.release-version }}-linux-${{ matrix.target-arch }}.tar.xz


  dragonflybsd:
    needs: base

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target-version: ['6.4']

    steps:
      - uses: actions/checkout@v4

      - uses: vmactions/dragonflybsd-vm@v1
        with:
          release: "${{ matrix.target-version }}.0"
          usesh: true
          sync: rsync
          copyback: true
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            run ./ppkg setup --syspm
            run ./ppkg update
            run ./ppkg install uppm@0.15.4 --static
            run ./ppkg bundle  uppm@0.15.4 .tar.xz

            for item in *.c
            do
              cc -std=c99 -Os -flto -Wl,-s -static -o "${item%.c}.exe" "$item"
            done

      - run: ./pack-ppkg-core ${{ needs.base.outputs.release-version }} dragonflybsd-${{ matrix.target-version }}-x86_64

      - uses: actions/upload-artifact@v4
        with:
          name: ppkg-core-${{ needs.base.outputs.release-version }}-dragonflybsd-${{ matrix.target-version }}-x86_64.tar.xz
          path: ppkg-core-${{ needs.base.outputs.release-version }}-dragonflybsd-${{ matrix.target-version }}-x86_64.tar.xz


  freebsd:
    needs: base

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target-version: ['14.2', '14.1', '14.0', '13.4', '13.3', '13.2']
        # https://archive.freebsd.org/old-releases/amd64/

    steps:
      - uses: actions/checkout@v4

      - uses: cross-platform-actions/action@master
        with:
          operating_system: freebsd
          version: ${{ matrix.target-version }}
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            run ./ppkg setup --syspm
            run ./ppkg update
            run ./ppkg install uppm@0.15.4 --static --profile=debug
            run ./ppkg bundle  uppm@0.15.4 .tar.xz

            for item in *.c
            do
              cc -std=c99 -Os -flto -Wl,-s -static -o "${item%.c}.exe" "$item"
            done

      - run: ./pack-ppkg-core ${{ needs.base.outputs.release-version }} freebsd-${{ matrix.target-version }}-amd64

      - uses: actions/upload-artifact@v4
        with:
          name: ppkg-core-${{ needs.base.outputs.release-version }}-freebsd-${{ matrix.target-version }}-amd64.tar.xz
          path: ppkg-core-${{ needs.base.outputs.release-version }}-freebsd-${{ matrix.target-version }}-amd64.tar.xz


  openbsd:
    needs: base

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        openbsd-version: ['7.6', '7.5', '7.4', '7.3', '7.2']
        # https://cdn.openbsd.org/pub/OpenBSD/

    steps:
      - uses: actions/checkout@v4

      - uses: cross-platform-actions/action@master
        with:
          operating_system: openbsd
          version: ${{ matrix.openbsd-version }}
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            run ./ppkg setup --syspm
            run ./ppkg update
            run ./ppkg install uppm@0.15.4
            run ./ppkg bundle  uppm@0.15.4 .tar.xz

            for item in *.c
            do
              cc -std=c99 -Os -flto -Wl,-s -static -o "${item%.c}.exe" "$item"
            done

      - run: ./pack-ppkg-core ${{ needs.base.outputs.release-version }} openbsd-${{ matrix.target-version }}-amd64

      - uses: actions/upload-artifact@v4
        with:
          name: ppkg-core-${{ needs.base.outputs.release-version }}-openbsd-${{ matrix.openbsd-version }}-amd64.tar.xz
          path: ppkg-core-${{ needs.base.outputs.release-version }}-openbsd-${{ matrix.openbsd-version }}-amd64.tar.xz


  netbsd:
    needs: base

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        target-version: ['10.0', '9.4', '9.3', '9.2']
        # https://ftp.netbsd.org/pub/NetBSD/

    steps:
      - uses: actions/checkout@v4

      - run: curl -LO https://curl.se/ca/cacert.pem

      - uses: cross-platform-actions/action@v0.26.0
        with:
          operating_system: netbsd
          version: ${{ matrix.target-version }}
          shell: bash
          run: |
            run() {
              printf "\033[0;35m==>\033[0m \033[0;32m%b\n\033[0m" "$*"
              eval "$@"
            }

            run export SSL_CERT_FILE="$PWD/cacert.pem"

            run ./ppkg setup --syspm
            run ./ppkg update
            run ./ppkg install uppm@0.15.4 --static
            run ./ppkg bundle  uppm@0.15.4 .tar.xz

            for item in *.c
            do
              cc -std=c99 -Os -flto -Wl,-s -static -o "${item%.c}.exe" "$item"
            done

      - run: ./pack-ppkg-core ${{ needs.base.outputs.release-version }} netbsd-${{ matrix.target-version }}-amd64

      - uses: actions/upload-artifact@v4
        with:
          name: ppkg-core-${{ needs.base.outputs.release-version }}-netbsd-${{ matrix.target-version }}-amd64.tar.xz
          path: ppkg-core-${{ needs.base.outputs.release-version }}-netbsd-${{ matrix.target-version }}-amd64.tar.xz


  publish:

    needs: [base, linux, macos, dragonflybsd, freebsd, openbsd, netbsd]

    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: '*'
          path: .
          merge-multiple: true

      - run: ls -a

      # to avaid: failed to run git: fatal: not a git repository (or any of the parent directories): .git
      - run: git -c init.defaultBranch=master init
      - run: git remote add origin ${{ github.repositoryUrl }}

      - run: |
          cat > notes.md <<EOF
          sha256sum:

          \`\`\`
          $(sha256sum ppkg-core-*.tar.xz)
          \`\`\`
          EOF

      - run: gh release create ppkg-core-${{ needs.base.outputs.release-version }} ppkg-core-*.tar.xz --title ppkg-core-${{ needs.base.outputs.release-version }} --notes-file notes.md
