name: valgrind

on:
  push:
    branches: [ c ]
  pull_request:
    branches: [ c ]

jobs:
  valgrind:

    runs-on: ubuntu-latest

    container: ubuntu:22.04

    env:
      VALGRIND: valgrind --leak-check=full --show-leak-kinds=all --track-origins=yes --verbose --error-exitcode=1

    steps:
      - uses: actions/checkout@main

      - run:  apt -y update
      - run:  apt -y install valgrind cmake ninja-build pkg-config g++ linux-headers-generic  curl zip unzip tar git

      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with:
          repository: microsoft/vcpkg
          path: vcpkg

      - run:  cd vcpkg && ./bootstrap-vcpkg.sh

      - run:  cd vcpkg && ./vcpkg install curl openssl libgit2 libarchive libyaml jansson zlib

      - run:  |
          cmake \
              -S . \
              -B build.d \
              -G Ninja \
              -DCMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake \
              -DCMAKE_INSTALL_PREFIX=./output \
              -DCMAKE_VERBOSE_MAKEFILE=ON \
              -DCMAKE_BUILD_TYPE=Debug

      - run:  cmake --build   build.d
      - run:  cmake --install build.d


      - run: $VALGRIND ./output/bin/ppkg

      - run: $VALGRIND ./output/bin/ppkg --help
      - run: $VALGRIND ./output/bin/ppkg -h

      - run: $VALGRIND ./output/bin/ppkg --version
      - run: $VALGRIND ./output/bin/ppkg -V

      - run: $VALGRIND ./output/bin/ppkg setup -v

      - run: $VALGRIND ./output/bin/ppkg env
      - run: $VALGRIND ./output/bin/ppkg env -v

      - run: $VALGRIND ./output/bin/ppkg integrate zsh
      - run: $VALGRIND ./output/bin/ppkg integrate zsh -v

      - run: $VALGRIND ./output/bin/ppkg update

      - run: $VALGRIND ./output/bin/ppkg search lib
      - run: $VALGRIND ./output/bin/ppkg search zip

      - run: $VALGRIND ./output/bin/ppkg info-available libzip
      - run: $VALGRIND ./output/bin/ppkg info-available libzip --yaml
      - run: $VALGRIND ./output/bin/ppkg info-available libzip --json
      - run: $VALGRIND ./output/bin/ppkg info-available libzip summary
      - run: $VALGRIND ./output/bin/ppkg info-available libzip version
      - run: $VALGRIND ./output/bin/ppkg info-available libzip license
      - run: $VALGRIND ./output/bin/ppkg info-available libzip web-url
      - run: $VALGRIND ./output/bin/ppkg info-available libzip src-url
      - run: $VALGRIND ./output/bin/ppkg info-available libzip src-sha

      - run: $VALGRIND ./output/bin/ppkg depends libzip
      - run: $VALGRIND ./output/bin/ppkg depends libzip -t dot
      - run: $VALGRIND ./output/bin/ppkg depends libzip -t box

      - run: $VALGRIND ./output/bin/ppkg fetch gzip
      - run: $VALGRIND ./output/bin/ppkg fetch gsed -v

      - run: apt -y install g++ linux-headers-generic

      - run: $VALGRIND ./output/bin/ppkg install libzip

      - run: $VALGRIND ./output/bin/ppkg tree libzip

      - run: $VALGRIND ./output/bin/ppkg info-installed libzip --prefix
      - run: $VALGRIND ./output/bin/ppkg info-installed libzip --files
      - run: $VALGRIND ./output/bin/ppkg info-installed libzip --json
      - run: $VALGRIND ./output/bin/ppkg info-installed libzip --yaml
      - run: $VALGRIND ./output/bin/ppkg info-installed libzip builtat
      - run: $VALGRIND ./output/bin/ppkg info-installed libzip builtat-iso-8601
      - run: $VALGRIND ./output/bin/ppkg info-installed libzip builtat-rfc-3339
      - run: $VALGRIND ./output/bin/ppkg info-installed libzip version

      - run: $VALGRIND ./output/bin/ppkg pack libzip
      - run: $VALGRIND ./output/bin/ppkg pack libzip -t tar.gz
      - run: $VALGRIND ./output/bin/ppkg pack libzip -t tar.lz
      - run: $VALGRIND ./output/bin/ppkg pack libzip -t tar.xz
      - run: $VALGRIND ./output/bin/ppkg pack libzip -t tar.bz2
      - run: $VALGRIND ./output/bin/ppkg pack libzip -t zip

      - run: |
          printf '%s\n' 'version: 1000' >> ~/.ppkg/repos.d/official-core/formula/libzip.yml

      - run: $VALGRIND ./output/bin/ppkg ls-available
      - run: $VALGRIND ./output/bin/ppkg ls-installed
      - run: $VALGRIND ./output/bin/ppkg ls-outdated

      - run: $VALGRIND ./output/bin/ppkg is-available libzip
      - run: $VALGRIND ./output/bin/ppkg is-installed libzip
      - run: $VALGRIND ./output/bin/ppkg is-outdated  libzip

      - run: $VALGRIND ./output/bin/ppkg upgrade   libzip
      - run: $VALGRIND ./output/bin/ppkg reinstall libzip
      - run: $VALGRIND ./output/bin/ppkg uninstall libzip

      - run: $VALGRIND ./output/bin/ppkg formula-repo-list
      - run: $VALGRIND ./output/bin/ppkg formula-repo-add my_repo https://github.com/leleliu008/ppkg-formula-repository-official-core
      - run: $VALGRIND ./output/bin/ppkg formula-repo-list
      - run: $VALGRIND ./output/bin/ppkg formula-repo-del my_repo

      - run: $VALGRIND ./output/bin/ppkg cleanup

        #- run: $VALGRIND ./output/bin/ppkg upgrade-self
